### ISSUE TITLE
getting exception when i click on menu button

### ISSUE THREAD

**Issue by ysvganesh** [Yalantis/Side-Menu.iOS#1]
hi

i'm getting exception when i click on menu button, i followed all manual installation please help me 

MenuExample[1050:25994] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a segue class named '_TtC8SideMenu9MenuSegue''
*** First throw call stack:
(
	0   CoreFoundation                      0x002a3946 __exceptionPreprocess + 182
	1   libobjc.A.dylib                     0x020d5a97 objc_exception_throw + 44
	2   UIKit                               0x015299dc -[UIStoryboardSegueTemplate segueWithDestinationViewController:] + 0
	3   UIKit                               0x01529a02 -[UIStoryboardSegueTemplate segueWithDestinationViewController:] + 38
	4   UIKit                               0x01529ade -[UIStoryboardSegueTemplate _perform:] + 110
	5   UIKit                               0x01529bc5 -[UIStoryboardSegueTemplate perform:] + 116
	6   libobjc.A.dylib                     0x020eb7cd -[NSObject performSelector:withObject:withObject:] + 84
	7   UIKit                               0x00f0e23d -[UIApplication sendAction:to:from:forEvent:] + 99
	8   UIKit                               0x00f0e1cf -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 64
	9   UIKit                               0x01041e86 -[UIControl sendAction:to:forEvent:] + 69
	10  UIKit                               0x010422a3 -[UIControl _sendActionsForEvents:withEvent:] + 598
	11  UIKit                               0x0104150d -[UIControl touchesEnded:withEvent:] + 660
	12  UIKit                               0x00f5e60a -[UIWindow _sendTouchesForEvent:] + 874
	13  UIKit                               0x00f5f0e5 -[UIWindow sendEvent:] + 791
	14  UIKit                               0x00f24549 -[UIApplication sendEvent:] + 242
	15  UIKit                               0x00f3437e _UIApplicationHandleEventFromQueueEvent + 20690
	16  UIKit                               0x00f08b19 _UIApplicationHandleEventQueue + 2206
	17  CoreFoundation                      0x001c71df __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 15
	18  CoreFoundation                      0x001bcced __CFRunLoopDoSources0 + 253
	19  CoreFoundation                      0x001bc248 __CFRunLoopRun + 952
	20  CoreFoundation                      0x001bbbcb CFRunLoopRunSpecific + 443
	21  CoreFoundation                      0x001bb9fb CFRunLoopRunInMode + 123
	22  GraphicsServices                    0x04b7b24f GSEventRunModal + 192
	23  GraphicsServices                    0x04b7b08c GSEventRun + 104
	24  UIKit                               0x00f0c8b6 UIApplicationMain + 1526
	25  MenuExample                         0x000a6aee top_level_code + 78
	26  MenuExample                         0x000a6b2b main + 43
	27  libdyld.dylib                       0x02842ac9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by advantis** [comment]
The manual installation instruction has been updated with the missing step: you have link your binary with SideMenu framework (9cf533f905e9bfdea0eb64fcf3c2d9214b5528f2)
