### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by JayachandraA** [Yalantis/Side-Menu.iOS#12]
I want to use [Sourcegraph](https://sourcegraph.com) for Side-Menu.iOS code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/Yalantis/Side-Menu.iOS. (It should only take 30 seconds.)

Thank you!

**Comment by KaterynaZaikina** [comment]
@JayachandraA Unfortunately, we don't use Sourcegraph but we'll consider this issue.

**Comment by AndrewiOS** [comment]
@JayachandraA  Unfortunately, "SWIFT IS NOT YET SUPPORTED" there
