### ISSUE TITLE
Exists a way to close the menu tapping outside the menu? 

### ISSUE THREAD

**Issue by juancholt** [Yalantis/Side-Menu.iOS#16]
Im working on a an app for events, and im using your library to show up a simple side menu, but, as the menu doesn't cover all screen, i need to dismiss the menu just by tapping anywhere(area outside the menu can be overlayed by a kind of translucent black or something) outside the menu or just tapping over cancel button

**Comment by EgorSobko** [comment]
@juancholt Hi, sorry for a delay, we've implemented  a new functionality that should satisfy your request, please read a new Usage guide for more information
