### ISSUE TITLE
Xcode Error: No such module SideMenu

### ISSUE THREAD

**Issue by ghost** [Yalantis/Side-Menu.iOS#17]
upon adding  'import SideMenu' in the view controller just after import UIKit (as per instructions) Xcode shows error 'No such module SideMenu'. Grateful for feedback.

**Comment by shanmarkus** [comment]
Try Clean and Build

**Comment by EgorSobko** [comment]
@MazenKilani Hi, do you use cocoapods to install SideMenu? If you install manually, try remove SideMenu.xcodeproj from your project and add it again.

**Comment by MazenKilani** [comment]
Used Cocoapods. Great utility, poor implementation (or they assume everyone is already an expert). I used John-Lluch/SWRevealViewController and customized it. Works like a dream.

**Comment by EgorSobko** [comment]
@ghost A new version has been released, try it, if you will meet this kind of trouble, try Option+Command+Shift+K in Xcode.
