### ISSUE TITLE
Better documentation 

### ISSUE THREAD

**Issue by mcdappdev** [Yalantis/Side-Menu.iOS#21]
Please support the rewriting of the documentation for this repository. It would be useful to many people that cannot digest all of the framework requirements just from the example project.

**Comment by kyegeorge** [comment]
I strongly agree with this comment

**Comment by EgorSobko** [comment]
@mcdappdev Hi, we've added some more functionality and made a new documentation. If you'll have some troubles in understanding, please tell us about this, we will try to describe installation and usage more precisely
