### ISSUE TITLE
Enable Scroll

### ISSUE THREAD

**Issue by pranavpari** [Yalantis/Side-Menu.iOS#28]
Hello,
How I can enable the scroll for menu? Because in my case the last cell is displayed only half so I want to enable the scroll for that.

Thank you

**Comment by KaterynaZaikina** [comment]
Hi, Pranav
Please, check 'Scrolling Enabled' for tableView in your MenuViewController in Storyboard, it should be enabled.

**Comment by pranavpari** [comment]
Hello,
Thank for the reply actually the scroll is working but the last cell in
showing only half.

On Tue, Mar 15, 2016 at 5:24 PM, Kateryna Zaikina <notifications@github.com>
wrote:

> Hi, Pranav
> Please, check 'Scrolling Enabled' for tableView in your MenuViewController
> in Storyboard, it should be enabled.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Yalantis/Side-Menu.iOS/issues/28#issuecomment-196786512
>



-- 
*Thanks & Regards,*

*Pranav Goswami.Mo: +91 8000 672 007*
*Website: pranavgoswami.com <http://pranavgoswami.com>*
*Skype:pranav_goswami01*

**Comment by AndrewiOS** [comment]
@pranavpari Can you provide more information? Try to start example project on iPhone 4s simulator, scroll works well for me in this case.

**Comment by pranavpari** [comment]
Ok thanks I will check

On Thu, May 19, 2016 at 7:56 PM, AndrewiOS <notifications@github.com> wrote:

> @pranavpari <https://github.com/pranavpari> Can you provide more
> information? Try to start example project on iPhone 4s simulator, scroll
> works well for me in this case.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Yalantis/Side-Menu.iOS/issues/28#issuecomment-220340460>
>



-- 
*Thanks & Regards,*

*Pranav Goswami.Mo: +91 8000 672 007*
*Website: pranavgoswami.com <http://pranavgoswami.com>*
*Skype:pranav_goswami01*
