### ISSUE TITLE
Crashing when push to another controller

### ISSUE THREAD

**Issue by Raghvendra7** [Yalantis/Side-Menu.iOS#30]
Menu is working fine but when i push from main screen to another controller 
CircularRevealTransitionAnimator crashes bcoz it not been initialised  found nil until we move to another screen of the through menu.
Once we move to another menu screen through menu it work fine
i have a case when user move to another screen from main screen without opening the menu.It crashed
Pls provide a solution
![screen shot 2016-03-31 at 11 55 40 am](https://cloud.githubusercontent.com/assets/10459999/14167338/2973d33c-f738-11e5-91be-b4b10ce92886.png)

**Comment by cabaret** [comment]
I'm also stuck on this. Any ideas? I want to move to another view controller after tapping on a tableviewcell and I'm getting the same crash as @Raghvendra7

**Comment by EgorSobko** [comment]
@Raghvendra7 Could you please tell me what transitionPoint you have at this moment. As for me, it's nil, thats why it crashes. You can implement code like this to avoid unsafe code:
`if let transitionPoint = transitionPoint {
            return CircularRevealTransitionAnimator(center: transitionPoint)
        }
        return nil`
