### ISSUE TITLE
No such module "SideMenu"

### ISSUE THREAD

**Issue by swatirahane17** [Yalantis/Side-Menu.iOS#35]
Hi ,
I am new in swift, i tried to use your Side-Menu.IOS, i follow all the steps but when i import SideMenu, it show me error- "No Such Module SideMenu". I am using ios 9 and Xcode 7.2.
I tried to set Framework Search Path , but its not work because the framework show different path when i  see its path in inspector. It show me path -"/Users/element45/Library/Developer/Xcode/DerivedData/sideMenuExample-frlseoygwmkbgyavakwulipeqlda/Build/Products/Debug-iphoneos/SideMenu.framework".
when i check on terminal i don't get the folder Debug-iphoneos.

**Comment by Roman-Scherbakov** [comment]
Hi, @swatirahane17. Did you use cocoa pod for install or manual installation?

**Comment by Junaidofficial** [comment]
Use Cocoa Pod for installiation.
First in the terminal write:

sudo gem install cocoapods

Then from the terminal goto you iOS App project directory where there is yourapp.xcodproj file is located. Then in terminal write:

     pod init
     open -s Xcode Podfile

A podfile will be opened, in that under your app targets write:
     pod 'YALSideMenu'

After saving it, go back to terminal and write:
     pod install

This will automatically download YALSlideMenu and install it and then link it to your project.
Thanks, hope this answers your problem.

**Comment by serejahh** [comment]
Hi @swatirahane17. Do you need some help? Has your problem been solved?
