### ISSUE TITLE
Support Swift 3

### ISSUE THREAD

**Issue by lubos08** [Yalantis/Side-Menu.iOS#39]
I got this error in my pod project.

`/Library/Developer/Xcode/DerivedData/Test-brtdskyfgtyqulfxwzmaflpehpwc/Build/Products/Debug-iphonesimulator/YALSideMenu/SideMenu.framework/SideMenu compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64`

Can you create new version for swift 3?
Or you already created it?

Thanks for creating such a great library.

**Comment by felipecarreramo** [comment]
any update about this?

**Comment by serejahh** [comment]
Update is coming 😄

**Comment by serejahh** [comment]
`2.0` is available in cocoapods
