### ISSUE TITLE
Side menu + Navigation bar

### ISSUE THREAD

**Issue by Eliottiosdevs** [Yalantis/Side-Menu.iOS#44]
Hi,

First, have a great year.
Nice side menu, like all your other work, it is AMAZING!
Is there any way i can use this with a navigation bar?
Because i would appreciate it and would like to use it with it.

Thanks in advance,
Eliott Hauteclair

**Comment by serejahh** [comment]
Hi @Eliottiosdevs. Thanks for your interest. The example app is implemented using navigation controller. You can show a navigation bar and then menu appears above the navigation bar

**Comment by Eliottiosdevs** [comment]
Ok thanks!
