### ISSUE TITLE
How to show AlertViewController?

### ISSUE THREAD

**Issue by nickgreetzly** [Yalantis/Side-Menu.iOS#45]
## Report a bug

> I can't show AlertViewController on navigator object.
###  What did you do?

> I tried all different options to get the viewcontroller from uinavigationcontroller and navigator object but its not working.
### What did you expect to happen?

> It should show the alert on the screen.
### What happened instead?

> Nothing happened.

**Comment by serejahh** [comment]
Hi @nickgreetzly

Open [ViewController](https://github.com/Yalantis/Side-Menu.iOS/blob/master/MenuExample/Controller/ViewController.swift) and add
``` swift
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    
    let alertViewController = UIAlertController(title: "works", message: nil, preferredStyle: .alert)
    present(alertViewController, animated: true, completion: nil)
}
```
and you'll see the alert
