### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by manulete19** [Yalantis/Side-Menu.iOS#46]
Hello,

First of all, thanks for provide us all this stuff. You save us a lot of hours.

I am using Swift 2.3 so I have followed steps in branch 2.3, but when I add throw CocoaPods 
**pod 'YALSideMenu'**, when I open the app in XCode I get a bunch of errors (arround 30). I don´t know if I´m doing something wrong or what is happening. I would really apreciate if you could help me.

Thanks in advance!!

**Comment by rohanvasishth** [comment]
Well from what you have written I think you might have installed the wrong pod. The pod you should install is: pod 'YALSideMenu', '~> 2.0' not pod 'YALSideMenu'. What I would suggest is that you uninstall the current pod and then reinstall it with the correct pod I have shown you. Here is a post that can help you with that: http://stackoverflow.com/questions/13751147/remove-or-uninstall-library-previously-added-cocoapods

**Comment by serejahh** [comment]
Currently we don't support swift 2.3, sorry

**Comment by rohanvasishth** [comment]
I am using swift 3 currently
