### ISSUE TITLE
import sidemenu --- No such module 'SideMenu'

### ISSUE THREAD

**Issue by joelbertlive** [Yalantis/Side-Menu.iOS#48]
<img width="1278" alt="screen shot 2017-03-12 at 6 07 29 pm" src="https://cloud.githubusercontent.com/assets/5482265/23838070/c7e4e8ea-074e-11e7-916f-2383d9842d96.png">

# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_
- iOS version: _insert here_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by panduranga2016** [comment]
Build the project and then you can work without any error.

**Comment by akaran95** [comment]
Import Foundation , it will resolve your problem.
