### ISSUE TITLE
Forces override on UIViewControllerAnimatedTransitioning methods then crashes

### ISSUE THREAD

**Issue by TheBachelor** [Yalantis/Side-Menu.iOS#50]
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What did you do? 

I tried to make delegate methods as your documentation says, but it forces me to add 'override' to each of the two methods. When I do, it runs but crashes. When I leave out both methods it does the same.

### What did you expect to happen?

I expected the menu to pop up like in the demo project (which had no errors). I even tried to copy the classes from the demo but they have errors when I add them to my project.

### What happened instead?

It crashed & has this error: Redundant conformance of 'ViewController' to protocol 'UIViewControllerTransitioningDelegate'

### Your Environment

- Version of the component: 2.0 & 2.0.1
- Swift version: 3.0
- iOS version: 10.3
- Device: iPhone 7 Simulator
- Xcode version: 8.3.2
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

n/a

**Comment by SerjOxo** [comment]
@TheBachelor Hi, thanks for your report. Can you give more information about your issue?

**Comment by freaqed** [comment]
Hey, @TheBachelor!
If you still facing the issue please feel free to reopen it and add some code snippets
