### ISSUE TITLE
SideMenu is not presented in iOS 9.3, X-Code - 9

### ISSUE THREAD

**Issue by panduranga2016** [Yalantis/Side-Menu.iOS#53]
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> Please describe what you want to add to the component. 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_ swift 3.0
- iOS version: _insert here_ 9.3
- Device: _insert here_ Simulator
- Xcode version: _insert here_ 9.0
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_  cocoa pods
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug
[MenuAnimationSuccess.zip](https://github.com/Yalantis/Side-Menu.iOS/files/1422227/MenuAnimationSuccess.zip)

> Please add a link to a project we can download that reproduces the bug.

**Comment by SerjOxo** [comment]
@panduranga2016 Hello! Please, check your storyboard and `func prepare(for segue: UIStoryboardSegue, sender: Any?)` in `ViewController` class. You made some mistakes there.

**Comment by panduranga2016** [comment]
Thanks for  your response.

Regards
Panduranga Mallipudi
