### ISSUE TITLE
Doesn't work if first viewcontroller is child of navigationcontroller

### ISSUE THREAD

**Issue by nitishrana28** [Yalantis/Side-Menu.iOS#55]
**# Report a bug :**

I have a navigationController at the beginning. On adding menu button on the navigationController's first viewController, the animation takes place in a full screen.
The example shown makes a simple viewController as the first viewController.

**# Expectations :**

It should behave in the same way as it does in a simple viewController

**## What happened instead?**

Attached screenshot :

![screen shot 2017-12-25 at 10 59 33 pm](https://user-images.githubusercontent.com/1484780/34341894-52fe7058-e9c7-11e7-8d47-3c1e870ff0d7.png)
![screen shot 2017-12-25 at 10 59 39 pm](https://user-images.githubusercontent.com/1484780/34341897-5b2b1790-e9c7-11e7-8000-3345f00cf91e.png)

***********

To confirm, I used menu button in another viewController(which was not embedded in UINavigationController), and it worked fine.

**### Your Environment**

- Version of the component: _insert here_
- Swift version: 4.0.3
- iOS version: 11.2
- Device: iPhone 5s
- Xcode version: 9.2

I ran the latest pods in my project

**Comment by chinmaykdas** [comment]
Please present modally. It is working as expected.
This is not an issue.
