### ISSUE TITLE
in swift 4 .sidemenu animation how to do that..

### ISSUE THREAD

**Issue by satish1219** [Yalantis/Side-Menu.iOS#57]
# Report

> The more information you provide, the faster we can help you.

⚠️ Select what you want - **a feature request** or **report a bug**. Please remove the section you aren't interested in.

###  What do you want to add?

> side menu animation exactly what your showing in your image 

### How should it look like?

> Please add images. 

###  What did you do?

> Please replace this with what you did. 

### What did you expect to happen?

> Please replace this with what you expected to happen.  

### What happened instead?

> Please replace this with what happened instead.

### Your Environment

- Version of the component: _insert here_
- Swift version: _insert here_
- iOS version: _insert here_
- Device: _insert here_
- Xcode version: _insert here_
- If you use Cocoapods: _run `pod env | pbcopy` and insert here_ 
- If you use Carthage: _run `carthage version | pbcopy` and insert here_

### Project that demonstrates the bug

> Please add a link to a project we can download that reproduces the bug.

**Comment by satish1219** [comment]
I want to add side menu animation exactly what you are showing on the image.
same as your image.

**Comment by Vodolazkyi** [comment]
Did you check our example ? Thanks

**Comment by indhraScena** [comment]
will it works on swift 4.1 and xcode 9.3

**Comment by rnkyr** [comment]
please refer to tag `2.1` (not in the tunk yet but will be available soon)
