### ISSUE TITLE
Menu example not working

### ISSUE THREAD

**Issue by gaurav1981** [Yalantis/Side-Menu.iOS#6]
Hi,
I recently cloned the repo and was trying to play with menuexample. I also followed ur instructions on manual installation, to the word as mentioned on your repository. But yet, i am facing following issues:
2015-04-30 18:40:45.550 MenuExample[61607:60b] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UITableViewCell 0x7ff6e0c69540> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key layoutMargins.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105865495 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001073d199e objc_exception_throw + 43
	2   CoreFoundation                      0x00000001058e9919 -[NSException raise] + 9
	3   Foundation                          0x0000000105d59530 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 259
	4   UIKit                               0x0000000106446569 -[UIView(CALayerDelegate) setValue:forKey:] + 149
	5   CoreFoundation                      0x0000000105861400 -[NSArray makeObjectsPerformSelector:] + 224
	6   UIKit                               0x0000000106641893 -[UINib instantiateWithOwner:options:] + 1112
	7   UIKit                               0x00000001064dbb0c -[UIViewController _loadViewFromNibNamed:bundle:] + 245
	8   UIKit                               0x00000001064dc149 -[UIViewController loadView] + 112
	9   UIKit                               0x000000010665c646 -[UITableViewController loadView] + 77
	10  UIKit                               0x00000001064dc3b7 -[UIViewController loadViewIfRequired] + 75
	11  UIKit                               0x00000001064dc777 -[UIViewController view] + 29
	12  UIKit                               0x00000001064ea11a -[UIViewController shouldAutorotate] + 30
	13  UIKit                               0x00000001064ea402 -[UIViewController _preferredInterfaceOrientationForPresentationInWindow:fromInterfaceOrientation:] + 236
	14  UIKit                               0x0000000106738519 -[UIWindowController transition:fromViewController:toViewController:target:didEndSelector:animation:] + 1798
	15  UIKit                               0x00000001064e6fce -[UIViewController presentViewController:withTransition:completion:] + 4854
	16  SideMenu                            0x000000010576af36 _TFC8SideMenu9MenuSegue7performfS0_FT_T_ + 1270
	17  SideMenu                            0x000000010576b082 _TToFC8SideMenu9MenuSegue7performfS0_FT_T_ + 34
	18  UIKit                               0x00000001063e7f06 -[UIApplication sendAction:to:from:forEvent:] + 80
	19  UIKit                               0x00000001063e7eb4 -[UIApplication sendAction:toTarget:fromSender:forEvent:] + 17
	20  UIKit                               0x00000001064c4880 -[UIControl _sendActionsForEvents:withEvent:] + 203
	21  UIKit                               0x00000001064c3dc0 -[UIControl touchesEnded:withEvent:] + 530
	22  UIKit                               0x000000010641ed05 -[UIWindow _sendTouchesForEvent:] + 701
	23  UIKit                               0x000000010641f6e4 -[UIWindow sendEvent:] + 925
	24  UIKit                               0x00000001063f729a -[UIApplication sendEvent:] + 211
	25  UIKit                               0x00000001063e4aed _UIApplicationHandleEventQueue + 9579
	26  CoreFoundation                      0x00000001057f4d21 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	27  CoreFoundation                      0x00000001057f45f2 __CFRunLoopDoSources0 + 242
	28  CoreFoundation                      0x000000010581046f __CFRunLoopRun + 767
	29  CoreFoundation                      0x000000010580fd83 CFRunLoopRunSpecific + 467
	30  GraphicsServices                    0x0000000108bddf04 GSEventRunModal + 161
	31  UIKit                               0x00000001063e6e33 UIApplicationMain + 1010
	32  MenuExample                         0x00000001056d2c3e top_level_code + 78
	33  MenuExample                         0x00000001056d2c7a main + 42
	34  libdyld.dylib                       0x0000000107d1d5fd start + 1
	35  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 

Quick: note i am new to swift and trying to see if i can run the example and then use this control in an objective C project. Can you please help me, this is quite urgent, since my client has used android version of this control for their android app and they prefer to use this in the iOS app as well.

**Comment by EgorSobko** [comment]
@gaurav1981 Hi, sorry for a such delay. Please, check your storyboard controllers' classes and connection of all their outlets. We've just merged a new version of menu, tested manual installation, everything works fine
